---
title: "Notebook to check your code changes before submitting PR"
---

# Perform package checks 

```{r}
library(devtools)
```
```{r}
Rcpp::compileAttributes(verbose = T)
```

## Documentation files will be generated
```{r}
devtools::document()
```

## A lot of different checks of your code

```{r}
devtools::check()
```

# Install from your branch
ensure you unloaded the package, removed the previous version and restarted the R session.
```{r}
devtools::install_github("artyomovlab/DualSimplex@theta_optimization_revised")
library(DualSimplex)
```

# Test run

## Create object
```{r fig.height = 5, fig.width = 11}
library(dplyr)

n_ct <- 3

set.seed(3)
sim <- create_simulation(n_genes = 10000,
                         n_samples = 100,
                         n_cell_types = n_ct,
                         with_marker_genes = FALSE)
sim <- sim %>% add_noise(noise_deviation = 0.2)

data_raw <- sim$data
true_basis <- sim$basis
true_proportions <- sim$proportions

dso <- DualSimplexSolver$new()
dso$set_data(data_raw)

plane_distance_threshold = 0.05 # Change here several times to see result, start with big and lower it
dso$project(3)
dso$distance_filter(plane_d_lt = plane_distance_threshold,
                    zero_d_lt = NULL,
                    genes = T)

dso$project(3)
dso$plot_svd_history()
dso$init_solution("random")
dso$plot_projected(
  "zero_distance",
  "zero_distance",
  with_solution = TRUE,
  use_dims = list(2:3)
)
```


## Make specific init, which was in a paper
```{r}
set.seed(23)
dso$init_solution("random")
dso$plot_projected(
  "plane_distance",
  "plane_distance",
  with_solution = TRUE,
  use_dims = list(2:3)
)
```
```{r}
dso$plot_projected(
  color_genes="green",
  "zero_distance",
  with_solution = TRUE,
  use_dims = list(2:3)
)
```
```{r}
genes <- T
color = "red"
anno <- get_anno(dso$st$data, genes)
      if (is.character(color) && length(color) == 1) {
        if (!is.null(dso$st$solution) && (color %in% colnames(dso$st$solution$W))) {
          name <- color
          if (genes) {
            color <- log(dso$st$solution$W[, color] + 1)
          } else {
            color <- dso$st$solution$H[color, ]
          }
        } else if (genes && !is.null(dso$st$marker_genes) && (color == "markers")) {
          name <- color
          color <- which_marker(rownames(dso$st$data), dso$st$marker_genes)
        } else if (color %in% colnames(anno)) {
          name <- color
          color <- anno[, color]
        } else if (color %in% rownames(anno)) {
          name <-  "individual_highlight"
        } else {
          name <- "direct_single_color"
        }
      } else {
        name <- NULL
      }
```

```{r}
get_color_params <- function(to_plot, color, color_name) {
  base_color <-  "black"
  if (is.null(color)) {
    return(list(
      color_vec = NULL,
      color_name = NULL,
      color_scheme = "default",
      base_color = base_color
    ))
  }

  if (is.null(color_name)) color_name <- "annotation"
  if (length(color[[1]]) > 1) color <- unlist(color)

  if (length(color) == nrow(to_plot)) {
    if (is.factor(color) || is.logical(color)) {
      return(list(
        color_vec = color,
        color_name = color_name,
        color_scheme = "factor",
        base_color = NULL
      ))
    } else {
      return(list(
        color_vec = color,
        color_name = color_name,
        color_scheme = "direct_multiple_colors",
        base_color = NULL
      ))
    }
  } else {
    if (color_name == "direct_single_color") {
      base_color <-  color
      return (list(
        color_vec = NULL,
        color_name = NULL,
        color_scheme = "direct_single_color",
        base_color = base_color
      ))
    }
    if (color_name == "individual_highlight") {
      color_name <- "highlight"
      return(list(
        color_vec = rownames(to_plot) %in% color,
        color_name = color_name,
        color_scheme = "highlight",
        base_color = base_color
    ))
    }
    if (color_name == "annotation")
    return(list(
      color_vec = rownames(to_plot) %in% color,
      color_name = "highlight",
      color_scheme = "highlight",
      base_color = base_color
    ))
  }
}
```

```{r}
color_name <-  name

points_2d <-  get_2d_subset(dso$st$proj, 2:3)[c("X")]

  to_plot <- as.data.frame(points_2d)
cp <- get_color_params(to_plot, color, color_name)

x_col <- colnames(to_plot)[1]
y_col <- colnames(to_plot)[2]
```

```{r}
library(ggplot2)
color_col <- cp$color_name

plt <- ggplot(to_plot, aes_string(x = x_col, y = y_col, color = color_col))
plt + geom_point(size = 1, color = cp$base_color) +geom_point(
        data = to_plot[to_plot[[color_col]], ],
        size = 1 * 2,
        alpha = 1,
        color = "green"
      )
```


```{r}
to_plot[, cp$color_name] <- cp$color_vec
```

## Make 5000 steps of optimization
```{r}
blocks <- 5
iterations <- 5000


for (i in 1:blocks) {
  dso$optim_solution(
    round(iterations / blocks),
    optim_config(
      coef_hinge_H = 1,
      coef_hinge_W = 1,
      coef_der_X = 0.001,
      coef_der_Omega = 0.001
    )
  )
  curr_X <- dso$st$solution_proj$X  # this is how we can extract solution on a fly
  curr_Omega <- dso$st$solution_proj$Omega # this is how we can extract solution on a fly
}
```

```{r fig.height = 5, fig.width = 11}
dso$plot_projected(
  "zero_distance",
  "zero_distance",
  with_solution = TRUE,
  use_dims = list(2:3)
)
```

```{r}
dso$plot_error_history()
```


## Prepare basis/proportions plots
```{r}
solution <- dso$finalize_solution()
names(solution)
solution <- dso$get_solution()
```

```{r fig.width=20, fig.height=5}
ptb <- coerce_pred_true_basis(solution$W, true_basis[rownames(solution$W), ])
ptp <- coerce_pred_true_props(solution$H, true_proportions)
plot_ptp_scatter(ptp)
plot_ptb_scatter(ptb)
```

```{r}
plot_ptp_lines(ptp)
```




```{r}
dso$init_solution("random")
res <-  dso$get_coordinates_from_external_matrices(true_basis, true_proportions)
```




## Check true solution
```{r}


X_result <- res$X
Omega_result <- res$Omega
```
```{r}
dso$init_solution("random")
```
```{r fig.width=5, fig.height=5}
library(ggplot2)
res_plots <- dso$plot_projected(use_dims = 2:3, with_solution = T, with_history = F, wrap = F, show_plots = F) 
res_plots[[1]] + geom_point(
    data = X_result,
    color = "purple",
    pch = 22,
    size = 3
  ) 


res_plots[[2]] + geom_point(
    data = Omega_result,
    color = "purple",
    pch = 22,
    size = 3
  ) 
```


```{r}
V <- data_raw
W <-  true_basis
H <- true_proportions
extended_scaling_result <- extended_sinkhorn(V, W, H, dso$st$scaling$iterations)

```
```{r}
Rcpp::sourceCpp(file = "test_cpp.cpp")
```

```{r}
extended_scaling_result <- extended_sinkhorn(V, W, H, dso$st$scaling$iterations)

```

```{r}
extended_scaling_result$
```

