---
title: "Linseed 2 Solver Summary"
output:
  html_document:
    df_print: paged
    self_contained: yes
params:
  lo2: !r NULL
---

<style>
img {
  height: 300px;
  width: auto;
}

h4 {
  margin-top: 20px;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.height = 5)
devtools::load_all()
```

```{r}
if (is.null(lo2$st$data))
  stop("Nothing was calculated yet")
```

Note: Dataset from the last set_data call is used.
### Filtering log

### Dataset
```{r results='asis'}
cat(nrow(lo2$get_data()), "genes x", ncol(lo2$get_data()), "samples")
```

```{r fig.width=7}
lo2$plot_svd(NULL) + ggtitle("SVD explained variance")
```

```{r fig.width=12, fig.height=3}
devtools::load_all()
plot_numeric_features(
  lo2$get_data(),
  T,
  features = c("log_mean", "log_median", "log_sd", "log_mad"),
  ncol = 4
)
```


```{r}
if (is.null(lo2$st$n_cell_types)) {
  knittr::knit_exit()
}
```

### Projection
```{r results='asis'}
cat(lo2$st$n_cell_types, "cell types selected")
```

```{r fig.width = 12}
lo2$plot_projected("zero_distance", "zero_distance", with_legend = T, with_solution = F, with_history = F)
```

```{r fig.width = 12}
lo2$plot_projected("plane_distance", "plane_distance", with_legend = T, with_solution = F, with_history = F)
```

```{r fig.width=12, fig.height=3}
plot_numeric_features(lo2$get_data(), T, features = c("plane_distance", "zero_distance"), ncol = 4, label = "Gene distances", bins = 100)
plot_numeric_features(lo2$get_data(), F, features = c("plane_distance", "zero_distance"), ncol = 4, label = "Sample distances", bins = 30)
```

```{r fig.width=8, fig.height=4}
plotlist <- list(
  plot_feature_pair(lo2$get_data(), "plane_distance", "zero_distance", T, size = 0.1),
  plot_feature_pair(lo2$get_data(), "plane_distance", "zero_distance", F, size = 0.1)
)
cowplot::plot_grid(plotlist = plotlist, ncol = 2)
```


```{r}
if (is.null(lo2$st$solution_proj)) {
  knittr::knit_exit()
}
has_optim = "optim_history" %in% names(lo2$st$solution_proj)
```

`r if (has_optim) {"### Optimization history"}`

```{r, eval=has_optim}
lo2$plot_error_history() + ggtitle("Error history")
```

```{r, eval=has_optim}
lo2$plot_projected(with_legend = F, with_solution = T, with_history = T)
```

```{r, eval=has_optim}
lo2$plot_projected(NULL, NULL, with_legend = F, with_solution = T, with_history = T)
```


### Solution
```{r}
lo2$plot_projected(with_legend = F, with_solution = T, with_history = F)
```

```{r fig.height=3, fig.width=6}
plot_proportions_distribution(solution$H)
plot_basis_distribution(solution$W)
```


### Cell types
Solution enrichment in genes and samples
```{r fig.height = 5, fig.width = 11}
for (ct in lo2$get_ct_names()) {
  show(lo2$plot_projected(
    ct,
    ct,
    pt_opacity = 1,
    with_legend = T,
    with_solution = T,
    with_history = F
  ))
}
```

### Marker genes
```{r fig.height = 5, fig.width = 11}
lo2$plot_projected(color_genes = "markers", color_samples = NULL, with_solution = T, with_history = F)
```


```{r}
# TODO: filtering tables
# TODO: heatmaps
# TODO: save to phantasus
# TODO: boxplots
# TODO: gradient maps
# TODO: save bases and signatures

# TODO: multiple inits
# TODO: proportions by 
```

