---
title: "R Notebook"
output: html_notebook
---

# Make Mixed Dataset


Note: maximum R version supported by CellMix is 3.6. But inserting installed package to newer versions of R seems to work fine.
(docker for this https://hub.docker.com/r/aladyevae/cellmix)

```{r}
 BiocManager::install('GEOquery')
# BiocManager::install('Metrics')
# BiocManager::install('uwot')
#BiocManager::install('tidyverse')
```

```{r}
library(CellMix)
library(digest)
library(GEOquery)
```

```{r}
DS_NAME <- "GSE11058"
n_markers <- 20
```

```{r}
GSE19830.em <- ExpressionMix("GSE11058", verbose=TRUE)
```

```{r}
props <- coef(GSE19830.em)

ex <- exprs(GSE19830.em)
bas <- basis(GSE19830.em)

ex <- ex[log2(apply(ex, 1, mad)) > 8, ]
bas <- bas[rownames(ex),]

cat(dim(ex), "\n")

data_full <- ex
colnames(bas) <- gsub(" |-", "_", colnames(bas))
```

## Save it to use in another R version

```{r}
saveRDS(GSE19830.em, "data_used/GSE11058_benchmark/single_run_em.rds")
saveRDS(bas, "data_used/GSE11058_benchmark/single_run_bas.rds")
saveRDS(props, "data_used/GSE11058_benchmark/single_run_props.rds")
saveRDS(data_full, "data_used/GSE11058_benchmark/single_run_data_full.rds")

```

## Multiple runs

```{r}
for (rep_n in seq(1,5)) {
  set.seed(rep_n)
  DS_NAME <- "GSE11058"
  GSE19830.em <- ExpressionMix("GSE11058", verbose=TRUE)
  props <- coef(GSE19830.em)
  ex <- exprs(GSE19830.em)
  bas <- basis(GSE19830.em)
  ex <- ex[sample(nrow(ex), nrow(ex)*0.8), ]
  ex <- ex[log2(apply(ex, 1, mad)) > 8, ]
  bas <- bas[rownames(ex),]
  data_full <- ex
  colnames(bas) <- gsub(" |-", "_", colnames(bas))
  rownames(props) <- gsub(" |-", "_", rownames(props))
  saveRDS(GSE19830.em, paste0("data_used/GSE11058_benchmark/",rep_n,"_run_em.rds"))
  saveRDS(bas, paste0("data_used/GSE11058_benchmark/",rep_n,"_run_bas.rds"))
  saveRDS(props, paste0("data_used/GSE11058_benchmark/",rep_n,"_run_props.rds"))
  saveRDS(data_full, paste0("data_used/GSE11058_benchmark/",rep_n,"_run_data_full.rds"))
}
```



